apiVersion: v1
kind: PersistentVolume
metadata:
    name: host-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    storageClassName: standard
    hostPath:
        path: /data
        type: DirectoryOrCreate
